### ISSUE TITLE
Load local plugins?

### ISSUE THREAD

**Issue by pianocomposer321** [aloussase/viper#3]
Thanks for your work on this plugin, I just switched my config over from a script I had hacked together that did very similar things, but much less elegantly, and so far I love it!

Do you have plans to add the ability to load/install plugins from a local directory rather than a remote git repo? I'm the author of a few plugins myself, so loading those from my machine while in development is really handy, not to mention having forks of other plugins, etc.

Thanks again!

**Comment by aloussase** [comment]
Hi there! Some time ago when I was using [paq](https://github.com/savq/paq-nvim) to manage my plugins I opened a similar issue on their repository. Their answer was that it was not necessary  because it is already quite easy to do it in neovim, and I agree with them. 

You can add your plugin to neovim's runtime path with a snippet like this: 
```lua
vim.opt.runtimepath:append('~/Code/myplugin')
```

Hope this is enough for you! Feel free to add any other comments or close the issue.
